package com.example

object LanguageManager {
    private val translations = mapOf(
        "AZ" to mapOf(
            "tab_library" to "Kitabxana",
            "tab_categories" to "Sirlər",
            "tab_settings" to "Ayarlar",
            "search_hint" to "Mahnı və ya ifaçı axtar...",
            "all_songs" to "BÜTÜN MAHNILAR",
            "play_on_startup" to "Girişdə ifa et",
            "scanning_storage" to "Yaddaş skan edilir...",
            "scanning_completed" to "mahnı tapıldı və siyahıya əlavə edildi.",
            "unknown_song" to "Naməlum Mahnı",
            "unknown_artist" to "<Naməlum İfaçı>",
            "unknown_album" to "Naməlum Albom",
            "now_playing" to "İndi Oynadılır",
            "sound_preset" to "Səs Preseti",
            "visualizer_style" to "Vizualizasiya",
            "preset_normal" to "Normal",
            "preset_bass" to "Bas Gücləndirici",
            "preset_spatial" to "Spatial 3D Səhnə",
            "preset_vocal" to "Vokal Təmiz",
            "preset_retro" to "Retro 8-Bit",
            "preset_normal_desc" to "Standart qüsursuz səs balansı",
            "preset_bass_desc" to "Aşağı tezliklərin (bas) dinamik artırılması",
            "preset_spatial_desc" to "Geniş və 3D akustik studiya simulyasiyası",
            "preset_vocal_desc" to "Danışıq və vokal detallarının aydınlaşdırılması",
            "preset_retro_desc" to "Tezliyin 8-bit retro oyun mühitinə uyğunlaşdırılması",
            "theme_selection" to "PREMİUM DİZAYN MÖVZULARI",
            "effects_title" to "SƏS COCO EFFEKTLƏRİ (DSP EQ)",
            "visualizer_title" to "PLEYERİN VİZUALİZATOR TƏRZİ",
            "developer_title" to "TƏRTİBATÇI",
            "dev_subtitle" to "Musiqi Pleyeri Tərtibatçısı",
            "dev_desc" to "Təmiz səs, nostalji estetika və qüsursuz istifadəçi təcrübəsi üçün yaradılmış bənzərsiz premium audio tətbiq.",
            "about_app" to "Tətbiq Haqqında",
            "about_desc" to "Aura Synth Player - yüksək səviyyəli səs, minimalist vizual və real-vaxt sintezator mühərriki ilə təchiz olunmuş premium musiqi pleyeridir.",
            "lyrics_empty" to "♫ Səssiz ritmlər fəzada süzülür...",
            "no_songs" to "Yüklənmiş mahnı yoxdur.",
            "no_songs_desc" to "Telefon yaddaşında MP3 tapılmadı. Sınaq üçün nümunə mahnı yarada bilərsiniz!",
            "searching_failed" to "Axtarışa uyğun musiqi tapılmadı.",
            "synth_secrets" to "Sintezator Sirləri!",
            "got_it" to "Anladım, Super!",
            "about_overlay_title" to "Səs Alqoritmləri haqqında",
            "back_button" to "Geri",
            "home_button" to "Ana Ekran",
            "lang_select" to "SİSTEM DİLİ",
            "lang_az" to "Azərbaycanca",
            "lang_en" to "English",
            "lang_tr" to "Türkçe",
            "lang_ru" to "Русский",
            "stats_title" to "SİSTEM STATİSTİKALARI",
            "stats_sample" to "Sintez Tezliyi: 11.0 kHz/16-bit PCM",
            "stats_tracks" to "Sintez olunmuş fayllar: %d ədəd",
            "smart_categories" to "SMART KATEQORİYALAR",
            "fav_rhythms" to "Mənim Sevimli Ritmlərim",
            "fav_empty" to "Sevimlilər siyahınız boşdur.\nMahnı pleyerindəki ürək düyməsinə basaraq mahnıları bura əlavə edə bilərsiniz!",
            "visualizer_pillars" to "Pillələr",
            "visualizer_waves" to "Dalğalar",
            "visualizer_lazer" to "Lazer",
            "visualizer_spheres" to "Kürələr",
            "song_scanned" to "Mahnı faylları skan olunur...",
            "info" to "Məlumat",
            "about_dialog_body" to "Bu premium musiqi pleyeri optimal bas gücləndirmə, retro 8-bit, normal, vokal təmizləmə filteri və 3D fəza səhnəsi ilə zənginləşdirilmişdir. Proqram daxilindəki sınaq mahnıları riyazi olaraq birbaşa kod tərəfindən 16-bitlik PCM dalğaları ilə yaradılır və hər hansı internet bağlantısı tələb etməz."
        ),
        "EN" to mapOf(
            "tab_library" to "Library",
            "tab_categories" to "Discover",
            "tab_settings" to "Settings",
            "search_hint" to "Search songs or artists...",
            "all_songs" to "ALL SONGS",
            "play_on_startup" to "Auto-play on startup",
            "scanning_storage" to "Scanning storage...",
            "scanning_completed" to "songs found and loaded successfully.",
            "unknown_song" to "Unknown Song",
            "unknown_artist" to "<Unknown Artist>",
            "unknown_album" to "Unknown Album",
            "now_playing" to "Now Playing",
            "sound_preset" to "Sound Preset",
            "visualizer_style" to "Visualizer",
            "preset_normal" to "Normal",
            "preset_bass" to "Bass Booster",
            "preset_spatial" to "Spatial 3D Stage",
            "preset_vocal" to "Clear Vocal",
            "preset_retro" to "Retro 8-Bit",
            "preset_normal_desc" to "Standard optimal sound balance",
            "preset_bass_desc" to "Dynamic amplification of low frequencies",
            "preset_spatial_desc" to "Broad 3D acoustic acoustic stage simulation",
            "preset_vocal_desc" to "Enhanced speech clarity and vocal details",
            "preset_retro_desc" to "8-bit nostalgic retro game audio emulation",
            "theme_selection" to "PREMIUM DESIGN THEMES",
            "effects_title" to "AUDIO COCO EFFECTS (DSP EQ)",
            "visualizer_title" to "PLAYER VISUALIZER STYLE",
            "developer_title" to "DEVELOPER",
            "dev_subtitle" to "Music Player Engineer",
            "dev_desc" to "A unique premium audio application crafted for pure sound, nostalgic aesthetics, and impeccable user experience.",
            "about_app" to "About Application",
            "about_desc" to "Aura Synth Player is a premium hardware music player loaded with superior sound filters, minimal aesthetics, and real-time algorithm sound syntonizers.",
            "lyrics_empty" to "♫ Silent rhythms float in space...",
            "no_songs" to "No songs found.",
            "no_songs_desc" to "No MP3 files found on your device. You can generate sample tracks to test the player!",
            "searching_failed" to "No matching music found.",
            "synth_secrets" to "Synthesizer Secrets!",
            "got_it" to "Got it, Super!",
            "about_overlay_title" to "Audio Algorithms Details",
            "back_button" to "Back",
            "home_button" to "Home",
            "lang_select" to "SYSTEM LANGUAGE",
            "lang_az" to "Azərbaycanca",
            "lang_en" to "English",
            "lang_tr" to "Türkçe",
            "lang_ru" to "Русский",
            "stats_title" to "SYSTEM AUDIT LOGS",
            "stats_sample" to "Sampling Rate: 11.0 kHz/16-bit PCM",
            "stats_tracks" to "Synthesized Files: %d tracks",
            "smart_categories" to "SMART CATEGORIES",
            "fav_rhythms" to "My Favorite Rhythms",
            "fav_empty" to "Your favorites list is empty.\nAdd tracks here by tapping the heart icon in the main music player overlay!",
            "visualizer_pillars" to "Pillars",
            "visualizer_waves" to "Waves",
            "visualizer_lazer" to "Laser",
            "visualizer_spheres" to "Cyber Beat",
            "song_scanned" to "Scanning song files...",
            "info" to "Information",
            "about_dialog_body" to "This premium music player is packed with optimal bass boost, nostalgic 8-bit emulation, normal studio tune, vocal filter, and spatial 3D stage acoustic enhancement. Demo tracks are dynamically synthesized directly from local mathematical equations into 16-bit PCM waves, requiring completely zero internet connectivity."
        ),
        "TR" to mapOf(
            "tab_library" to "Kütüphane",
            "tab_categories" to "Keşfet",
            "tab_settings" to "Ayarlar",
            "search_hint" to "Şarkı veya sanatçı ara...",
            "all_songs" to "TÜM ŞARKILAR",
            "play_on_startup" to "Açılışta oynat",
            "scanning_storage" to "Hafıza taranıyor...",
            "scanning_completed" to "şarkı bulundu ve başarıyla yüklendi.",
            "unknown_song" to "Bilinmeyen Şarkı",
            "unknown_artist" to "<Bilinmeyen Sanatçı>",
            "unknown_album" to "Bilinmeyen Albüm",
            "now_playing" to "Şimdi Çalıyor",
            "sound_preset" to "Ses Profili",
            "visualizer_style" to "Görselleştirici",
            "preset_normal" to "Normal",
            "preset_bass" to "Bas Güçlendirici",
            "preset_spatial" to "Uzamsal 3D Sahne",
            "preset_vocal" to "Pürüzsüz Vokal",
            "preset_retro" to "Retro 8-Bit",
            "preset_normal_desc" to "Standart kusursuz ses dengesi",
            "preset_bass_desc" to "Düşük frekansların (bas) dinamik olarak artırılması",
            "preset_spatial_desc" to "Geniş ve 3D akustik stüdyo simülasyonu",
            "preset_vocal_desc" to "Konuşma ve vokal detaylarının netleştirilmesi",
            "preset_retro_desc" to "Frekansın 8-bit retro oyun ortamına emülasyonu",
            "theme_selection" to "PREMIUM TASARIM TEMALARI",
            "effects_title" to "SES COCO ETKİLERİ (DSP EQ)",
            "visualizer_title" to "OYNATICI GÖRSELLEŞTİRME STİLİ",
            "developer_title" to "GELİŞTİRİCİ",
            "dev_subtitle" to "Müzik Çalar Geliştiricisi",
            "dev_desc" to "Saf ses kalitesi, nostaljik tasarım ve kusursuz bir kullanıcı deneyimi üretimi için optimize edilmiş benzersiz pleyer.",
            "about_app" to "Uygulama Hakkında",
            "about_desc" to "Aura Synth Player - gelişmiş ses filtreleri, minimalist görsel efektler ve gerçek zamanlı matematiksel sentezleyici motoru barındıran üst düzey bir müzik oynatıcıdır.",
            "lyrics_empty" to "♫ Sessiz ritimler boşlukta süzülüyor...",
            "no_songs" to "Yüklenmiş şarkı bulunamadı.",
            "no_songs_desc" to "Cihazınızda MP3 şarkı dosyası yok. Oynatıcıyı test etmek için örnek parçalar sentezleyebilirsiniz!",
            "searching_failed" to "Aramaya uygun müzik bulunamadı.",
            "synth_secrets" to "Sentezleyici Sırları!",
            "got_it" to "Anladım, Harika!",
            "about_overlay_title" to "Ses Algoritmaları hakkında",
            "back_button" to "Geri",
            "home_button" to "Anasayfa",
            "lang_select" to "SİSTEM DİLİ",
            "lang_az" to "Azərbaycanca",
            "lang_en" to "English",
            "lang_tr" to "Türkçe",
            "lang_ru" to "Русский",
            "stats_title" to "SİSTEM İSTATİSTİKLERİ",
            "stats_sample" to "Sentez Frekansı: 11.0 kHz/16-bit PCM",
            "stats_tracks" to "Sentezlenmiş Dosya: %d parça",
            "smart_categories" to "AKILLI KATEGORİLER",
            "fav_rhythms" to "Favori Ritimlerim",
            "fav_empty" to "Yıldızlı listeniz henüz boş.\nMüzik çalardaki kalp simgesine tıklayarak buraya parça ekleyebilirsiniz!",
            "visualizer_pillars" to "Sütunlar",
            "visualizer_waves" to "Dalgalar",
            "visualizer_lazer" to "Lazer",
            "visualizer_spheres" to "Küreler",
            "song_scanned" to "Müzik dosyaları taranıyor...",
            "info" to "Bilgi",
            "about_dialog_body" to "Bu üstün nitelikli müzik oynatıcı; bas desteği, nostaljik retro 8-bit emülatör, orijinal stüdyo tonlaması, net vokal modu ve 3D uzamsal akustik mekan zenginleşimiyle inşa edilmiştir. Uygulama içi test şarkıları matematiksel formüllerle doğrudan cihazınızda 16-bit PCM dalgasıyla üretilir ve hiçbir internet gerektirmez."
        ),
        "RU" to mapOf(
            "tab_library" to "Библиотека",
            "tab_categories" to "Обзор",
            "tab_settings" to "Настройки",
            "search_hint" to "Поиск песен или артистов...",
            "all_songs" to "ВСЕ ПЕСНИ",
            "play_on_startup" to "Играть при запуске",
            "scanning_storage" to "Сканирование памяти...",
            "scanning_completed" to "песен успешно найдено и загружено.",
            "unknown_song" to "Неизвестная песня",
            "unknown_artist" to "<Неизвестный исполнитель>",
            "unknown_album" to "Неизвестный альбом",
            "now_playing" to "Сейчас играет",
            "sound_preset" to "Звуковой пресет",
            "visualizer_style" to "Визуализация",
            "preset_normal" to "Обычный",
            "preset_bass" to "Усиление басов",
            "preset_spatial" to "Пространственная 3D сцена",
            "preset_vocal" to "Чистый вокал",
            "preset_retro" to "Ретро 8-бит",
            "preset_normal_desc" to "Стандартный сбалансированный студийный звук",
            "preset_bass_desc" to "Динамическая накачка низких частот (баса)",
            "preset_spatial_desc" to "Широкая симуляция 3D стереопанорамы студии",
            "preset_vocal_desc" to "Оптимальная проработка голоса и чистота речи",
            "preset_retro_desc" to "Эмуляция ностальгического 8-битного звучания ретро-игр",
            "theme_selection" to "ПРЕМИАЛЬНЫЕ ЦВЕТОВЫЕ ТЕМЫ",
            "effects_title" to "ЭФФЕКТЫ ОБРАБОТКИ ЗВУКА (DSP EQ)",
            "visualizer_title" to "СТИЛЬ ВИЗУАЛИЗАЦИИ ПЛЕЕРА",
            "developer_title" to "РАЗРАБОТЧИК",
            "dev_subtitle" to "Инженер аудио-систем",
            "dev_desc" to "Уникальное музыкальное приложение, созданное ради совершенной чистоты звука, аналоговой эстетики и безупречной эргономики.",
            "about_app" to "О приложении",
            "about_desc" to "Aura Synth Player - это звуковой плеер премиум-класса с высокотехнологичными фильтрами звука, минималистичной графикой и встроенным алгоритмом оффлайн-синтеза.",
            "lyrics_empty" to "♫ Тихие ритмы парят в пространстве...",
            "no_songs" to "Нет загруженных песен.",
            "no_songs_desc" to "Аудиозаписи во внешней памяти не найдены. Вы можете сгенерировать демо-треки для тестирования!",
            "searching_failed" to "Музыка по запросу не найдена.",
            "synth_secrets" to "Секреты синтезатора!",
            "got_it" to "Понятно, Отлично!",
            "about_overlay_title" to "Аудио Алгоритмы",
            "back_button" to "Назад",
            "home_button" to "Главный экран",
            "lang_select" to "ЯЗЫК СИСТЕМЫ",
            "lang_az" to "Azərbaycanca",
            "lang_en" to "English",
            "lang_tr" to "Türkçe",
            "lang_ru" to "Русский",
            "stats_title" to "СИСТЕМНЫЕ ПОКАЗАТЕЛИ",
            "stats_sample" to "Частота синтеза: 11.0 кГц / 16-бит PCM",
            "stats_tracks" to "Синтезировано файлов: элементов: %d",
            "smart_categories" to "УМНЫЕ КАТЕГОРИИ",
            "fav_rhythms" to "Мои любимые ритмы",
            "fav_empty" to "Ваш список избранного пуст.\nДобавьте треки сюда, нажав кнопку «сердечко» на экране проигрывателя!",
            "visualizer_pillars" to "Столбцы",
            "visualizer_waves" to "Волны",
            "visualizer_lazer" to "Лазер",
            "visualizer_spheres" to "Сферы",
            "song_scanned" to "Сканирование аудио файлов...",
            "info" to "Инфо",
            "about_dialog_body" to "Премиальный плеер оснащен качественными фильтрами усиления басов, эмуляции 8-битного ретро-звука, стандартным режимом, чистым вокалом и пространственной сценой 3D. Все демо-песни внутри программы математически рассчитываются формулами напрямую на чипе в несжатом 16-битном формате PCM и работают полностью оффлайн."
        )
    )

    fun get(key: String, languageCode: String): String {
        val strings = translations[languageCode] ?: translations["AZ"]!!
        return strings[key] ?: translations["AZ"]!![key] ?: key
    }
}
